logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} %L -%msg%n"
  level:
    com.netflix.discovery: 'INFO'
    org.springframework.cloud: 'WARN'

server:
  port: 8081
  contextPath: '/gaia'
  omcat:
    max-threads: 1000
    max-connections: 20000

spring:
  data:
    mongodb:
      #      database: gaia-new
      #      host: 127.0.0.1
      #      port: 27017
      database: gaia
      host: company-real-ip.pansy.pw
      port: 17017
      password: Asdf1357A1
      username: root
  http:
    multipart:
      max-file-size: 5MB # 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
      max-request-size: 5MB

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #url: jdbc:mysql://192.168.0.198/gaia?serverTimezone=Asia/Shanghai&useUnicode=true&useSSL=false
    url: jdbc:mysql://company-real-ip.pansy.pw:30219/giant?useUnicode=true&characterEncoding=utf-8&erverTimezone=GMT&useSSL=false

    username: giant
    password: giant

    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 50 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)

  redis:
    host: 127.0.0.1
    database: 0
    port: 6379
    password:
    pool:
      max-active: 200
      max-wait: 500
      max-idle: 10
      maxWait : 5000

customer:
  page: 19116
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath:/com/yudao/dao/mysql/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.yudao.model  # 注意：对应实体类的路径



