package com.yudao.entity;

import java.util.Date;

public class Account {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.id
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.phone
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.nick
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private String nick;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.type
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private Byte type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.backup_url
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private String backupUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.time
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.md5
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private String md5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.state
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private Byte state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.close_time
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private Date closeTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.platform_id
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private Integer platformId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.doued
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private Byte doued;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.dou
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private Integer dou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.ismy
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private String ismy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.kuai_id
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private String kuaiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.sprider_name
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private String spriderName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account.instance_name
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    private String instanceName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.id
     *
     * @return the value of account.id
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.id
     *
     * @param id the value for account.id
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.phone
     *
     * @return the value of account.phone
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.phone
     *
     * @param phone the value for account.phone
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.nick
     *
     * @return the value of account.nick
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.nick
     *
     * @param nick the value for account.nick
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setNick(String nick) {
        this.nick = nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.type
     *
     * @return the value of account.type
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.type
     *
     * @param type the value for account.type
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.backup_url
     *
     * @return the value of account.backup_url
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public String getBackupUrl() {
        return backupUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.backup_url
     *
     * @param backupUrl the value for account.backup_url
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setBackupUrl(String backupUrl) {
        this.backupUrl = backupUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.time
     *
     * @return the value of account.time
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.time
     *
     * @param time the value for account.time
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.md5
     *
     * @return the value of account.md5
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public String getMd5() {
        return md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.md5
     *
     * @param md5 the value for account.md5
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setMd5(String md5) {
        this.md5 = md5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.state
     *
     * @return the value of account.state
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.state
     *
     * @param state the value for account.state
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.close_time
     *
     * @return the value of account.close_time
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public Date getCloseTime() {
        return closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.close_time
     *
     * @param closeTime the value for account.close_time
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setCloseTime(Date closeTime) {
        this.closeTime = closeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.platform_id
     *
     * @return the value of account.platform_id
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public Integer getPlatformId() {
        return platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.platform_id
     *
     * @param platformId the value for account.platform_id
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setPlatformId(Integer platformId) {
        this.platformId = platformId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.doued
     *
     * @return the value of account.doued
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public Byte getDoued() {
        return doued;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.doued
     *
     * @param doued the value for account.doued
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setDoued(Byte doued) {
        this.doued = doued;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.dou
     *
     * @return the value of account.dou
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public Integer getDou() {
        return dou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.dou
     *
     * @param dou the value for account.dou
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setDou(Integer dou) {
        this.dou = dou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.ismy
     *
     * @return the value of account.ismy
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public String getIsmy() {
        return ismy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.ismy
     *
     * @param ismy the value for account.ismy
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setIsmy(String ismy) {
        this.ismy = ismy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.kuai_id
     *
     * @return the value of account.kuai_id
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public String getKuaiId() {
        return kuaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.kuai_id
     *
     * @param kuaiId the value for account.kuai_id
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setKuaiId(String kuaiId) {
        this.kuaiId = kuaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.sprider_name
     *
     * @return the value of account.sprider_name
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public String getSpriderName() {
        return spriderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.sprider_name
     *
     * @param spriderName the value for account.sprider_name
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setSpriderName(String spriderName) {
        this.spriderName = spriderName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account.instance_name
     *
     * @return the value of account.instance_name
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public String getInstanceName() {
        return instanceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account.instance_name
     *
     * @param instanceName the value for account.instance_name
     *
     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
     */
    public void setInstanceName(String instanceName) {
        this.instanceName = instanceName;
    }
}