package com.yudao.entity;

public class TaobaoPhone1 {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_phone1.phone
     *
     * @mbg.generated Wed Jan 15 10:26:38 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_phone1.uid
     *
     * @mbg.generated Wed Jan 15 10:26:38 CST 2020
     */
    private String uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column taobao_phone1.nick
     *
     * @mbg.generated Wed Jan 15 10:26:38 CST 2020
     */
    private String nick;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_phone1.phone
     *
     * @return the value of taobao_phone1.phone
     *
     * @mbg.generated Wed Jan 15 10:26:38 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_phone1.phone
     *
     * @param phone the value for taobao_phone1.phone
     *
     * @mbg.generated Wed Jan 15 10:26:38 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_phone1.uid
     *
     * @return the value of taobao_phone1.uid
     *
     * @mbg.generated Wed Jan 15 10:26:38 CST 2020
     */
    public String getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_phone1.uid
     *
     * @param uid the value for taobao_phone1.uid
     *
     * @mbg.generated Wed Jan 15 10:26:38 CST 2020
     */
    public void setUid(String uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column taobao_phone1.nick
     *
     * @return the value of taobao_phone1.nick
     *
     * @mbg.generated Wed Jan 15 10:26:38 CST 2020
     */
    public String getNick() {
        return nick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column taobao_phone1.nick
     *
     * @param nick the value for taobao_phone1.nick
     *
     * @mbg.generated Wed Jan 15 10:26:38 CST 2020
     */
    public void setNick(String nick) {
        this.nick = nick;
    }
}