//package com.yudao.dao.sql;
//
//import com.yudao.entity.Account;
//import com.yudao.entity.AccountExample;
//
//import java.util.List;
//
//import org.apache.ibatis.annotations.Param;
//
//public interface AccountMapper {
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table account
//     *
//     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
//     */
//    long countByExample(AccountExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table account
//     *
//     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
//     */
//    int deleteByExample(AccountExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table account
//     *
//     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
//     */
//    int deleteByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table account
//     *
//     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
//     */
//    int insert(Account record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table account
//     *
//     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
//     */
//    int insertSelective(Account record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table account
//     *
//     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
//     */
//    List<Account> selectByExample(AccountExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table account
//     *
//     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
//     */
//    Account selectByPrimaryKey(Integer id);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table account
//     *
//     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
//     */
//    int updateByExampleSelective(@Param("record") Account record, @Param("example") AccountExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table account
//     *
//     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
//     */
//    int updateByExample(@Param("record") Account record, @Param("example") AccountExample example);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table account
//     *
//     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
//     */
//    int updateByPrimaryKeySelective(Account record);
//
//    /**
//     * This method was generated by MyBatis Generator.
//     * This method corresponds to the database table account
//     *
//     * @mbg.generated Wed Oct 23 14:24:18 CST 2019
//     */
//    int updateByPrimaryKey(Account record);
//
//    /**
//     * 根据类型和条数  查询出对应的账号的信息
//     *
//     * @param type
//     * @param number
//     * @param instanceName
//     * @return
//     */
//    List<Account> getAccountByTypeAndNumber(@Param("type") Integer type, @Param("platformId") Integer platformId, @Param("number") Integer number, @Param("instanceName") String instanceName);
//
//    /**
//     * 根据搜索的条件进行查询
//     *
//     * @param start
//     * @param rows
//     * @param type
//     * @param account
//     * @param instanceName
//     * @param state
//     * @param ismy
//     * @return
//     */
//    List<Account> getAccountBySearchKey(@Param("start") Integer start,
//                                        @Param("rows") Integer rows,
//                                        @Param("type") Integer type,
//                                        @Param("account") String account,
//                                        @Param("platformId") Integer platformId,
//                                        @Param("instanceName") String instanceName,
//                                        @Param("state") Integer state,
//                                        @Param("ismy") Integer ismy);
//
//    Integer getCount(
//            @Param("type") Integer type,
//            @Param("account") String account,
//            @Param("platformId") Integer platformId,
//            @Param("instanceName") String instanceName,
//            @Param("state") Integer state,
//            @Param("ismy") Integer ismy);
//
//    /**
//     * 根据账号和类型进行状态的更新
//     *
//     * @param phone
//     * @param type
//     */
//    void updateAccountState(@Param("phone") String phone, @Param("type") Integer type, @Param("state") Integer state);
//
//
//    /**
//     * 通过平台的id获得账号的个数
//     *
//     * @param platformId
//     * @return
//     */
//    Integer getAccountByPlatformId(Integer platformId);
//
//    /**
//     * 获取有快手豆得账号
//     *
//     * @return
//     */
//    Account getHasKSDouAccount(@Param("type") Integer type, @Param("platformId") Integer platformId, @Param("instanceName") String instanceName);
//
//    /**
//     * 更新快手都得个数
//     *
//     * @param phone
//     * @param dou
//     */
//    void updateDou(@Param("phone") String phone, @Param("dou") Integer dou);
//
//    // 归还账号时，更新SpriderName
//    void updateGoBackSpriderName(String spriderName);
//}